[package]
name = "a2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
sv39 = ["libos/sv39"]
sv48 = ["libos/sv48"]

[dependencies]
libos = { path = "../../libos" }
